apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-release.fullname" . }}
  labels:
    {{- include "helm-release.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscalingPolicy }}
  replicas: 1
{{- end }}
  selector:
    matchLabels:
      {{- include "helm-release.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "helm-release.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-release.serviceAccountName" . }}
      securityContext:
        fsGroup: 65534
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.configMap }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
          {{- end }}
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          livenessProbe:
            {{ .Values.serviceHealth.livenessProbe | toYaml | indent 12 | trim }}
          readinessProbe:
            {{ .Values.serviceHealth.readinessProbe | toYaml | indent 12 | trim }}          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
