# (c) 2020 EPAM systems, Inc. All Right Reserved. All information contained herein is, and remains the
# property of EPAM Systems, Inc. and/or its suppliers and is protected by international intellectual
# property law. Dissemination of this information or reproduction of this material is strictly forbidden,
# unless prior written permission is obtained from EPAM Systems, Inc.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/strip-path: 'true'
  name: {{ include "helm-release.fullname" . }}
  labels:
{{- include "helm-release.labels" . | nindent 4 }}    
spec:
  ingressClassName: kong-internal
  rules:
  - host: mdtu-gpt-dev-internal.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: {{ .Values.env.SUFFIX }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: 8080
