{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-release.serviceAccountName" . }}
  labels:
    {{- include "helm-release.labels" . | nindent 4 }}

  {{- if or .Values.serviceAccount.annotations .Values.serviceAccount.addIamRole }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- if .Values.serviceAccount.addIamRole -}}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.awsaccountid }}:role/mosaic/{{ include "helm-release.serviceAccountName" . }}-service-account
    {{- end }}
  {{- end }}
  {{- end }}

 
{{- end }}
