{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-release.serviceAccountName" . }}
  labels:
    {{- include "helm-release.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.awsaccountid }}:role/mosaic/{{ include "helm-release.serviceAccountName" . }}-service-account
{{- end }}
