{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-release.serviceAccountName" . }}
  labels:
    {{- include "helm-release.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/mosaic/bop-fulfillment-po-ws-service-account
    {{ .Values.global-env-variables | toYaml | indent 4 | trim }}    
{{- end }}
