{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-release.serviceAccountName" . }}
  labels:
    {{- include "helm-release.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
#    eks.amazonaws.com/role-arn: {{ .Values.aws-account-id }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
