{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-release.serviceAccountName" . }}
  labels:
    {{- include "helm-release.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::984210178871:role/mosaic/bop-fulfillment-po-ws-service-account
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
