{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-release.fullname" . }}
  labels:
    {{- include "helm-release.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.configMap }}
{{ $key | quote | indent 6}}: {{ $val | quote }}
{{- end}}
{{- end -}}
